name: Trigger Multiple Workflows

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run multiple workflow dispatches dynamically
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: Bogyi2024/rapidgator
        run: |
          # Fetch the raw pastebin content (just the lines that are workflow dispatch commands)
          lines=$(curl -s https://pastebin.com/raw/gGFrt0Ci | grep -c '^gh workflow run')

          echo "Found $lines workflows to trigger."

          # Loop through line numbers and run commands accordingly
          for i in $(seq 1 $lines); do
            workflow_name="Ubuntu - Rapidgator_Multiline - line $i"
            echo "Triggering workflow: $workflow_name"
            gh workflow run "$workflow_name" --repo "$REPO"
            sleep 2
          done
