name: Trigger Multiple Workflows

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run multiple workflow dispatches with delays
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 1" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 2" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 3" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 4" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 5" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 6" --repo Bogyi2024/rapidgator
          sleep 2
          gh workflow run "Ubuntu - Rapidgator_Multiline - line 7" --repo Bogyi2024/rapidgator
